[package]
name = "prime-scripts"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde =  { version = "1", features = ["derive"] }
bincode = { version = "1" }
serde_json = "1"
serde_arrays = "0.1"
once_cell = "1"
serde_bytes = "0.11"
regex = "1"
